services:
  # PostgreSQL Database
  - type: pserv
    name: workwale-db
    env: docker
    plan: free
    region: ohio
    databases:
      - name: workwale
        user: workwale_user

  # FastAPI Backend
  - type: web
    name: workwale-backend
    env: python
    region: ohio
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: workwale-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: CORS_ORIGINS
        value: https://workwale-frontend.onrender.com

  # Next.js Frontend
  - type: web
    name: workwale-frontend
    env: node
    region: ohio
    plan: free
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "cd frontend && npm start"
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://workwale-backend.onrender.com
      - key: NODE_ENV
        value: production