services:
  # PostgreSQL Database
  - type: pserv
    name: workwale-db
    env: docker
    plan: free
    region: ohio
    databaseName: workwale
    databaseUser: workwale_user

  # FastAPI Backend
  - type: web
    name: workwale-backend
    env: python
    region: ohio
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: workwale-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: CORS_ORIGINS
        value: https://workwale-frontend.onrender.com

  # Next.js Frontend
  - type: web
    name: workwale-frontend
    env: node
    region: ohio
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://workwale-backend.onrender.com
      - key: NODE_ENV
        value: production